### ISSUE TITLE
[UTHM] Bootnodes Client 

### ISSUE THREAD

**Issue by drabdkadir** [iexplotech/IPTM_Bootnodes_Client#1]
D:\IPTM2020\IPTM_TESTNET2020\IPTM_Bootnodes_Client>echo UTHM-Sealer> nodeId.txt

D:\IPTM2020\IPTM_TESTNET2020\IPTM_Bootnodes_Client>dir
 Volume in drive D is New Volume
 Volume Serial Number is 3096-9ECC

 Directory of D:\IPTM2020\IPTM_TESTNET2020\IPTM_Bootnodes_Client

05/18/2020  01:44 PM    <DIR>          .
05/18/2020  01:44 PM    <DIR>          ..
05/18/2020  01:41 PM             1,714 .gitignore
05/18/2020  01:41 PM                36 InCmd_getEnodeId_DefaultEthAccount.txt
05/18/2020  01:41 PM            15,608 iptm_client.js
05/18/2020  01:44 PM                 0 iptm_client.log
05/18/2020  01:41 PM            35,823 LICENSE
05/18/2020  01:41 PM                 2 list_bootnodes.txt
05/18/2020  01:47 PM                13 nodeId.txt
05/18/2020  01:41 PM                 2 outCmd_getEnodeId_DefaultEthAccount.txt
05/18/2020  01:41 PM               351 README.md
               9 File(s)         53,549 bytes
               2 Dir(s)  1,056,273,477,632 bytes free

D:\IPTM2020\IPTM_TESTNET2020\IPTM_Bootnodes_Client>node iptm_client.js > iptm_client.log
'node' is not recognized as an internal or external command,
operable program or batch file.

**Comment by iexplotech** [comment]
Please install node js for windows. This version support for truffle tools.
https://nodejs.org/dist/latest-v10.x/node-v10.20.1-x64.msi
